apiVersion: apps/v1
kind: Deployment
metadata:
  name: expand
  namespace: uat
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: expand
  template:
    metadata:
      labels:
        app: expand
    spec:
      containers:
      - name: expand
        image: parmanand0712/expand:74df88c
        ports:
        - containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: expand-env-uat
