apiVersion: apps/v1
kind: Deployment
metadata:
  name: expand
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: expand
  template:
    metadata:
      labels:
        app: expand
    spec:
      containers:
      - image: parmanand0712/expand:v1
        name: expand
        ports:
        - containerPort: 3000
