apiVersion: apps/v1
kind: Deployment
metadata:
  name: expand-api
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: expand-api
  template:
    metadata:
      labels:
        app: expand-api
    spec:
      containers:
      - image: parmanand0712/expand-api:latest
        name: expand-api
        ports:
        - containerPort: 3000
